### ISSUE TITLE
Release v1.0.0 Roadmap

### ISSUE THREAD

**Issue by Nase00** [Nase00/pantheon#14]
- [ ] Comprehensive response handling when events are triggered.
- [ ] Handle Multiple Philips Hue bridges
- [ ] Handle Philips Hue RGB bulbs
- [ ] Handle multiple Unified Remote servers
- [ ] Increase test coverage to >70%
